### ISSUE TITLE
ServerErrorException not precise

### ISSUE THREAD

**Issue by SurendranathKhamavant** [voxeet/voxeet-uxkit-android#11]
**Describe the bug**

 Hello sir, I'm using the "then, then, catch" implementation from SDK 2.3.0 for opening a session, creating a conference and joining it. Sometimes the catch fetch an error "-1" without any description or reason from **ServerErrorException** class .
 Can it be more precise like for example an http code or something? It can help me a lot to display to my users why there was an error.
 Thank you sir.

**Expected Behaviour**

Have a more precise error workflow, or just an http code can be enough.

**Steps to Reproduce the Problem**

For example, joining and leaving a conference very fast is the easiest way to reproduce an error.

**Minimalistic code (recommended)**

```java
        VoxeetSDK.session().open(new ParticipantInfo(null, null, null))
                .then(new PromiseExec<Boolean, CreateConferenceResult>() {
                    @Override
                    public void onCall(@Nullable Boolean result, @NonNull Solver<CreateConferenceResult> solver) {
                        solver.resolve(VoxeetSDK.conference().create("test"));
                    }
                })
                .then(new PromiseExec<CreateConferenceResult, Conference>() {
                    @Override
                    public void onCall(@Nullable CreateConferenceResult result, @NonNull Solver<Conference> solver) {
                        // FIXME: THERE IS A WARNING HERE OF DEPRECIATION!!!
                        solver.resolve(VoxeetSDK.conference().join(result.conferenceId));
                    }
                })
                .then(new PromiseExec<Conference, Object>() {
                    @Override
                    public void onCall(@Nullable Conference result, @NonNull Solver<Object> solver) {
                           Log.d("talkApp", "SUCCESS");
                    }
                })
                .error(new ErrorPromise() {
                    @Override
                    public void onError(@NonNull Throwable e) {
                        // FIXME: SOME DIFFICULTY TO FETCH ERROR, SOMETIMES -1??
                        if (e instanceof ServerErrorException) {
                            ServerErrorException exception = (ServerErrorException) e;
                            ServerErrorMessage error = exception.error;

                            Log.d("talkApp", "ERROR => code: " + error.error_code + " description: " + error.error_description + " reason: " + error.error_reason);
                        }
                });
```

**Specifications**

  - Device: Simulator and Motorola
  - OS: Android Q and Androit 8
  - Platform: Android
  - Version:
    - [e.g. Android Sdk public-sdk 2.3.0]
    - [e.g. Android Sdk uxkit 2.1]

**Comment by codlab** [comment]
The -1 value is a generic error when no other information are available from either the server or http call

Using the ServerErrorException, you have the `origin` which tells you exactly which was the branch which failed

**Comment by SurendranathKhamavant** [comment]
I understand what's the exception.origin does, that's very useful to know where the exception happened but there is a regression in our project due to this new exception, before that we used the **HttpException** to handle correctly the voxeet sdk, it was very useful for us. Everything was working fine :)

 I tried to follow https://voxeet.com/documentation/sdk/release-notes/migration for java to bump my project to **2.3.0**.

 We just wanted to update this sdk to the latest version 2.3.0 without any regression if possible sir, thank you for your help.

**Comment by codlab** [comment]
This is not a regression, the HttpException is only being able to be consumed properly only one time and it gives information that are and must only be available internally from the SDK : Http exceptions can't be assumed from clients to be enough to give them state about the overall SDK's calls. Mking the use of the HttpException is not enough to catch the various SDK state anyway and removed from a direct access :

`before that we used the HttpException to handle correctly the voxeet sdk`

Does not give you the : 
- login state
- socket state
- current conference state known locally
- local and remote users events
etc...

If you want to give any informative state for the user, you must use every information above.

`For example, joining and leaving a conference very fast is the easiest way to reproduce an error.`

This is actually the expected behaviour. In such case, leaving must be considered, anyway, in a terminal state : everything from the local SDK point of view is cleared and won't keep the mic, camera etc... for instance. The only possible side effect being for other users where the user "could" still see the left user being in negotiation or joining until the server times out the left user. 

Joining a conference does not make the user completely inside the conference but the user could want to "cancel" (for instance) the call - hence the leaving method must be still available anytime.

**Comment by SurendranathKhamavant** [comment]
Understood sir, I may need to  update the HttpException part with my team for the new one...

Since which sdk version the new exception  ServerErrorException has been  introduced? We can't find it on https://voxeet.com/documentation/sdk/release-notes/changelog

But are we agree to say that it's not common  to have a ServerErrorException with error_code = -1 a null error_description and a null error_reason? It's maybe too generic...  We already have an issue on an other project, it was because the http response  contains nothing (no http body), if this can help you maybe...

Maybe if the http body contains nothing you can  set the error.error_code to the http code response? It can really help!

**Comment by codlab** [comment]
We could see if it can be interesting to bring such information for future releases but again. Those information are only a subset of everything that the SDK is already giving. hence using only the http part of the exception can't be as precise as everything provided by the SDK

See the getters and events from :
- [ConferenceService](https://www.voxeet.com/documentation/sdk/reference/android/conference)
- [SessionService](https://www.voxeet.com/documentation/sdk/reference/android/session)

**Comment by SurendranathKhamavant** [comment]
Thank you very much for  your consideration sir.

As an example we were explaining  that you can reproduce it by joining / leaving a conference very fast but in real life we experienced  some server down time on Apr 2 2020.
With your previous implementation, it was very  easy to fetch what was wrong. With the 2.3.0 implementation we can't for example say "hum something is wrong with our voip provider, servers are down, please come back later" we only know that **"-1"** error_code happened but we will not be sure anymore  if it's a  down time server issue or if it's just an error on a VoxeetSdk method... (I need to ask my team but I think we had some error 500 on april 2 2020)

 If our usage can help voxeet to improve  the ServerErrorException to maybe have an other object for example "exception.http_error"  we are glad that our workflow help!

_Also  sir can you provide us more detail about our previous question please: "Since which sdk version the new exception ServerErrorException has been introduced? We can't find it on https://voxeet.com/documentation/sdk/release-notes/changelog"_

**Comment by codlab** [comment]
You won't find it in the changelog and it's been introduced for at least the 2.0.4X+

`hum something is wrong with our voip provider, servers are down, please come back later`
The -1 is a generic error indicating the server is not sending any specific information or the request could not go through.

Again check the SDK state using the various getters and events, those are more reliable, stable and clear. What you want to do using it can't and won't deal with every cases.

For instance, error 500 can happen for various reasons even with server in a proper state : reauthentication needed but one of the call could not go through, with your logic where you assume a 500 means voxeet's error, you can't deal with such state. So even with prior SDKs, you couldn't say it either.

**Comment by SurendranathKhamavant** [comment]
Thank you sir for your help we figured out how to manage the new exception within our app.
We replaced our old error management with a generic one when the voxeet sdk throw:
```error_code = -1, error_description = null, error_reason = null```

If some improvements are made on this generic error, ping us here thank you.
