### ISSUE TITLE
Not able to pause or play video presentation

### ISSUE THREAD

**Issue by bjprogrammer** [voxeet/voxeet-uxkit-android#14]
It seems android voxeet sdk fires following api internally-
https://session.voxeet.com/v1/conferences/efxxxxx-xxxx-xxxx/filepresentation/pause

when calling this method-
Promise<VideoPresentation> promise = VoxeetSDK.videoPresentation().pause(100);
promise.execute();

From web I could see that correct url should have been -
https://session.voxeet.com/v1/conferences/efxxxxx-xxxxx-xxxx/videopresentation/pause
and its working on web

In android sdk IRestApiVideoPresentation.java file needs to be corrected.
@POST("/v1/conferences/{conferenceId}/videopresentation/start")
Call<ResponseBody> startVideoPresentation(@Path("conferenceId") String var1, @Body IRestApiVideoPresentation.VideoPresentationUrl var2);

@POST("/v1/conferences/{conferenceId}/videopresentation/stop")
Call<ResponseBody> stopVideoPresentation(@Path("conferenceId") String var1);

@POST("/v1/conferences/{conferenceId}/filepresentation/play")
Call<ResponseBody> playVideoPresentation(@Path("conferenceId") String var1);

@POST("/v1/conferences/{conferenceId}/filepresentation/pause")
Call<ResponseBody> pauseVideoPresentation(@Path("conferenceId") String var1, @Body IRestApiVideoPresentation.VideoPresentationSeek var2);

@POST("/v1/conferences/{conferenceId}/filepresentation/seek")
Call<ResponseBody> seekVideoPresentation(@Path("conferenceId") String var1, @Body IRestApiVideoPresentation.VideoPresentationSeek var2);

I think bottom three endpoints in above code need to be corrected. "filepresentation" needs to be changed to "videopresentation"

**Comment by codlab** [comment]
Will fix for the 3.0.3 coming mid December (circa)

**Comment by FabienLavocat** [comment]
Thank you @bjprogrammer & @codlab.
I have created an internal ticket and will follow up with you here.

**Comment by FabienLavocat** [comment]
The SDK 3.0.3 for Android has the fix. https://github.com/voxeet/voxeet-sdk-android#v303
