### ISSUE TITLE
Confusing UX in Speaker button

### ISSUE THREAD

**Issue by mattyg** [voxeet/voxeet-uxkit-android#15]
**Describe the bug**

The UX of the speaker button is confusing and misleading. When audio is playing out of the headphones, the speaker button is toggled "on", and when it is playing out of the speaker, it is toggled "off".

**Expected Behaviour**

Either the speaker button icon is changed to a have a "strikethrough" and the behavior stays the same, or the speaker button is toggled "on" when audio is playing out of the speaker, and toggled "off" otherwise.

**Steps to Reproduce the Problem**

See the minimalistic code example below.

**Minimalistic code (recommended)**

This repo (branch no-hud-video-bug) demonstrates the issue: https://github.com/mattyg/voxeet-cordova-example

Both devices used were on Android.

Follow the steps below to reproduce:

Device A: connect to voxeet

Device B: connect to voxeet
Device B: plug in headphones

Device A: create conference

Device A: invite user on device B

Device B: click "Accept" on incoming call notice

**Audio is playing out of headphones. Speaker button is toggled "on."**

Device B: remove headphones

**Audio is playing out of speaker. Speaker button is toggled "off."**

**Specifications**

Device: Android
OS: Android 8 & 9
Version: latest cordova-plugin-voxeet

**Comment by FabienLavocat** [comment]
I moved this issue to the voxeet-uxkit-android as it is related to the UXKit itself (not cordova)

**Comment by FabienLavocat** [comment]
Hi @mattyg I created a branch in my own repo for this request, the Pull Request is pending.
Feel free to use this branch for your project - https://github.com/FabienLavocat/voxeet-uxkit-android/tree/barbuttons
