### ISSUE TITLE
"Mixer" user is shown in users list in the top bar

### ISSUE THREAD

**Issue by youssmak** [voxeet/voxeet-uxkit-android#23]
**Describe the bug**

When liveRecording is set to true

**Expected Behaviour**

Do not show "Mixer" user in the users list

**Specifications**

  - Device: Honor 7X
  - OS: Android 8.0.0
  - Platform: Android

**Comment by FabienLavocat** [comment]
I am moving this issue to the *voxeet-uxkit-android* repo as it is coming from the native version rather than the Cordova or React Native layer.

**Comment by FabienLavocat** [comment]
Hi @youssmak thank you for reporting this issue, this has just been fixed by @codlab in this commit: https://github.com/voxeet/voxeet-uxkit-android/commit/2f0ca16908f862dc6d7fca8194da239858471726
It will be available in the next release of the UXKit.

**Comment by FabienLavocat** [comment]
Hi @youssmak, the issue is now fixed in the native UXKit for Android. We will publish a new version of the Cordova layer next week.
