### ISSUE TITLE
Speaker audio route with SDK v3

### ISSUE THREAD

**Issue by LarssonTech2** [voxeet/voxeet-uxkit-android#27]
**Describe the bug**

Hello, We have some trouble to understand audio route management with voxeet sdk **3.1.4**. Our workflow is the following, start a conference with a video and audio on the main speaker (not the phone one). Currently we have an issue when plugin our headset then unplug it, the speaker is reset on the phone. We don't use **requestaudiofocus** or **abandonaudiofocusrequest**, that's maybe the reason of our current behaviour? We also sometime have the main speaker audio route reseted to the phone without doing anything, so we came with a solution maybe not great to force the audio again and again, we are willing to some advices here so we can have a clean workflow.

**Expected Behaviour**

Main speaker always ON, but have the possibility to plug an headset and when it unplugged, go back to the main speaker. 

**Steps to Reproduce the Problem**

For the speaker disconnection, sometime just wait into a conference and then it is reseted without any reason.
For the headset, plug it and unplug it then the main speaker is reseted to the phone speaker.

**Minimalistic code (recommended)**

Here is some code:
```java
    private int resetAudioAttempts = 0; // property to help
    private final SoundManager.Call<List<MediaDevice>> onAudioDeviceUpdate = this::audioDeviceUpdated;

    ...
    setSpeaker(); // is called at the join response after open > create
    ...

    private void setSpeaker() {
        //  register audio 
        if (resetAudioAttempts == 0) {
            VoxeetSDK.audio().enable(); // not sure what is line does
            VoxeetSDK.audio().registerUpdateDevices(onAudioDeviceUpdate); // example found in the voxeetuxkit: private final SoundManager.Call<List<MediaDevice>> onAudioDeviceUpdate = this::audioDeviceUpdated;
        }

        // Set speaker  so enumerate devices to find EXTERNAL_SPEAKER and if it is connected
        VoxeetSDK.audio().enumerateDevices()
                .then((ThenPromise<List<MediaDevice>, Boolean>) mediaDevices -> {
                    MediaDevice speaker = Map.find(mediaDevices,
                            mediaDevice -> mediaDevice.deviceType() == DeviceType.EXTERNAL_SPEAKER
                                    && mediaDevice.platformConnectionState() == ConnectionState.CONNECTED);

                    if (null == speaker) {
                        throw new IllegalStateException("Impossible speaker");
                    }

                    return VoxeetSDK.audio().connect(speaker);
                })
                .error(error -> Log.d("codecappvideo", "Failed audio: " + error));
    }

// Maybe that's not the good solution here, we are trying to force the speaker
// called be: private final SoundManager.Call<List<MediaDevice>> onAudioDeviceUpdate = this::audioDeviceUpdated; 
    private void audioDeviceUpdated(List<MediaDevice> mediaDevices) {
        if (null == mediaDevices) return;

        for (MediaDevice mediaDevice : mediaDevices) {


            if (mediaDevice.deviceType() == DeviceType.EXTERNAL_SPEAKER) {
                if (mediaDevice.platformConnectionState() == ConnectionState.CONNECTED && mediaDevice.connectionState() == ConnectionState.DISCONNECTED) {

// asynchronously try to reset again the speaker
                    VoxeetSDK.audio().currentMediaDevice()
                            .then((ThenPromise<MediaDevice, Boolean>) currentMediaDevice -> {
                                // if there is no connected media device, reset speaker audio route ( with max 3 attempts).
                                if (null == currentMediaDevice && resetAudioAttempts <= 3) {
                                    resetAudioAttempts++;

                                    setSpeaker(); // recursive call

                                    Log.d("codecappvideo", "Audio device reconnection  " + resetAudioAttempts );
                                    
                                }
                                return Promise.resolve(true);
                            })
                            .error(error -> Log.d("codecappvideo", "Failed to get current media device: " + error));
                    break;
                } else {
                    resetAudioAttempts = 0;
                }
            }
        }
    }
```

So as you can see I don't think forcing the speaker is a good solution, we may have missed something in https://dolby.io/developers/interactivity-apis/reference/client-sdk/reference-android/audioservice or https://github.com/voxeet/voxeet-sdk-android-audio and we hope that you can help please.
Greetings

**Specifications**

  - Device: Samsung, Motorola, Huawei
  - OS: Android 7-10
  - Platform: Android
  - Version:
    - [e.g. Android Sdk public-sdk v3.1.4]
    - [e.g. Android Sdk uxkit v3.1.3]
  - Hardware:
    - [e.g. headset]

**Comment by codlab** [comment]
`Currently we have an issue when plugin our headset then unplug it, the speaker is reset on the phone` this is an expected behavior

There's a fix available in the audio sdk module used by the SDK. If you use `compile ('com.voxeet.sdk:audio:2.2.1')` whenever a switch from the wired headset is done, it will reflect as well (the speaker will still be disconnected because it's how the Android system is currently forcing things but at least you will know with a proper DISCONNECTED state from the external speaker MediaDevice)


As a sidenote, in your implementation, I would avoid the `VoxeetSDK.audio().currentMediaDevice()` since it would not show CONNECTING state ; thus making various unnecessary calls which could prevent "quick" behavior change. Using just `VoxeetSDK.audio().enumerateDevices()` and filtering for CONNECTING / CONNECTED devices, you could check easily what is currently be changing and have a cleaner and more maintainable implementation regarding the audio devices 👍

**Comment by LarssonTech2** [comment]
Thank you for your quick replay and clarifications @codlab.  So do we also need to add https://github.com/voxeet/voxeet-sdk-android-audio to our project or the sdk 3.1.4 is enough?
Ok understood as long as we know there is a change with DISCONNECTED state , then we can work with it. To catch this state do you recommend to use `VoxeetSDK.audio().registerUpdateDevices(onAudioDeviceUpdate);` or is there an other way to detect audio changes? ( like maybe this listener https://github.com/voxeet/voxeet-sdk-android-audio#instance? but do you have an example how to use it please? because it's not an interface but a promise ) 

Ok we will remove currentMediaDevice implementation, we were using it because it was given a different result and state but it wasn't a good way to do it properly as you told so.  Also do you know if this line is useful:
```java
VoxeetSDK.audio().enable(); // not sure what is line does
```

**Comment by codlab** [comment]
to catch the state, it's better to go with the registerUpdateDevices method which will always gives you updated list whenever an Audio SDK's state or platform wide's state has been changed

(the VoxeetSDK.audio().registerUpdateDevices is the best place to go because it's wrapping an instance for you.

The Voxeet's SDK 3.1.4 is not yet including this Audio SDK version, that's why you need to put this updated dependency alongside the Voxeet's SDK until a new version is released (there's not timeframe for now for this)

The currentMediaDevice is interesting but most of the time, the enumerateDevices is the best place to find everything because it will contain every transient state as well for any devices.

Concerning the enable method, it's there to enable or not everything related to the sounds to play during a conference (even with the custom sounds you may have registered in your app - note that it does not override any use of SoundPool or things available via the system, only the methods that the Voxeet's SDK provides in the AudioService)

**Comment by LarssonTech2** [comment]
Hello ok thank you for those answers. So after spending some time on it I came with this solution help by your advices to remove **currentMediaDevice** and use  **enumerateDevices** instead, it's starting to work quite well.   I need your advice if this implementation is on right track please, so I replace the content of the above method `private void audioDeviceUpdated(List<MediaDevice> mediaDevices) {` with:

```java
    private void audioDeviceUpdated(List<MediaDevice> mediaDevices) {
        VoxeetSDK.audio().enumerateDevices()
                .then((ThenPromise<List<MediaDevice>, Boolean>) enumeratedMediaDevices -> {
                    if (null == enumeratedMediaDevices) return Promise.resolve(true);

                    /* for Wired headset, priority number 1 */
                    for (MediaDevice mediaDevice : enumeratedMediaDevices) {
                        if (mediaDevice.deviceType() == DeviceType.WIRED_HEADSET && mediaDevice.platformConnectionState() == ConnectionState.CONNECTED) {

                            if (mediaDevice.connectionState() == ConnectionState.DISCONNECTED) {
                                return VoxeetSDK.audio().connect(mediaDevice);
                            }

                            return Promise.resolve(true);
                        }
                    }

                    /* for External speaker, priority number 2 */
                    for (MediaDevice mediaDevice : enumeratedMediaDevices) {
                        if (mediaDevice.deviceType() == DeviceType.EXTERNAL_SPEAKER && mediaDevice.platformConnectionState() == ConnectionState.CONNECTED) {

                            if (mediaDevice.connectionState() == ConnectionState.DISCONNECTED) {
                                return VoxeetSDK.audio().connect(mediaDevice);
                            }

                            return Promise.resolve(true);
                        }
                    }

                    return Promise.resolve(true);
                })
                .error(error -> Log.d("codecappvideo", "Failed to get current media device: " + error));
    }
```

With this implementation if an headset is connected it will prioritise it over the external speaker, what do you think about it?

**Comment by codlab** [comment]
you got the general idea. But this code won't work as expected, in case you want to have support for WIRED with higher priority and be always on EXTERNAL, you will need to do the following 

- no need to call the enumerateDevices inside the audioDeviceUpdated method, the list of the mediaDevices is always the update to date list of devices
- before the two loops, register a `Promise<Boolean> promise = null;`

- in the first loop, check for the `connectionState` of the WIRED headset, (keep the platformConnectionState() == CONNECTED check)
  - if it's CONNECTED/CONNECTING -> promise = Promise.resolve(true);
  - if it's DISCONNECTING/DISCONNECTED -> promise = Voxeet.audio().connect(mediaDevice);
  
- before the second loop, check if promise is not null, if not => return it
- in the second loop
  - you can get rid of the platformConnectionState, it will always be CONNECTED (there's always 1 external speaker)
  - if it's CONNECTED/CONNECTING -> promise = Promise.resolve(true);
  - if it's DISCONNECTING/DISCONNECTED -> promise = Voxeet.audio().connect(mediaDevice);

After this, it will work as expected in the scenario where WIRED > EXTERNAL SPEAKER > all other mode

**Comment by LarssonTech2** [comment]
Hello,

So we remove `mediaDevice.platformConnectionState() == ConnectionState.CONNECTED` for the speaker and we added bluetooth support and remove enumerateDevices, do you think we are good to go? 
Is the bluetooth support is good like that?
Don't you think it's risky to connect a device if the state is "disconnecting"?

```java
    private void audioDeviceUpdated(List<MediaDevice> mediaDevices) {
        if (null == mediaDevices) return; // need to be checked?

        Promise<Boolean> promise = null;  // as told by codlab

        /* for Wired headset, priority number 1 */
        for (MediaDevice mediaDevice : mediaDevices) {
            if (mediaDevice.deviceType() == DeviceType.WIRED_HEADSET && mediaDevice.platformConnectionState() == ConnectionState.CONNECTED) {
                if (mediaDevice.connectionState() == ConnectionState.DISCONNECTING || mediaDevice.connectionState() == ConnectionState.DISCONNECTED) {
                    promise = VoxeetSDK.audio().connect(mediaDevice);
                } else if (mediaDevice.connectionState() == ConnectionState.CONNECTING || mediaDevice.connectionState() == ConnectionState.CONNECTED) {
                    promise = Promise.resolve(true);
                }
                break;
            }
        }

        if (promise != null) { return; }

        /* for bluetooth, priority number 2 */
        for (MediaDevice mediaDevice : mediaDevices) {
            if (mediaDevice.deviceType() == DeviceType.BLUETOOTH && mediaDevice.platformConnectionState() == ConnectionState.CONNECTED) {
                if (mediaDevice.connectionState() == ConnectionState.DISCONNECTING || mediaDevice.connectionState() == ConnectionState.DISCONNECTED) {
                    promise = VoxeetSDK.audio().connect(mediaDevice);
                } else if (mediaDevice.connectionState() == ConnectionState.CONNECTING || mediaDevice.connectionState() == ConnectionState.CONNECTED) {
                    promise = Promise.resolve(true);
                }
                break;
            }
        }

        if (promise != null) { return; }

        /* for External speaker, priority number 3 */
        for (MediaDevice mediaDevice : mediaDevices) {
            if (mediaDevice.deviceType() == DeviceType.EXTERNAL_SPEAKER) { // remove mediaDevice.platformConnectionState() == ConnectionState.CONNECTED as told so. 
                if (mediaDevice.connectionState() == ConnectionState.DISCONNECTING || mediaDevice.connectionState() == ConnectionState.DISCONNECTED) {
                    promise = VoxeetSDK.audio().connect(mediaDevice);  //  maybe promise is useless
                } else if (mediaDevice.connectionState() == ConnectionState.CONNECTING || mediaDevice.connectionState() == ConnectionState.CONNECTED) {
                    promise = Promise.resolve(true);     //  maybe promise is useless
                }
                break;
            }
        }
```

**Comment by LarssonTech2** [comment]
Hello,

With the above implementation we have a bug, `mediaDevices` from `private void audioDeviceUpdated(List<MediaDevice> mediaDevices)` isn't allowing us to properly switch to the right device, that's why in our first implementation we preferred using `VoxeetSDK.audio().enumerateDevices()` which gives us the opportunity to switch to the right device. 

Is it a known issue?

**Comment by codlab** [comment]
your `if (promise != null) { return; }` and the end of your code won't do anything : the promise is not resolved -> no connection is then made. You need to use promise.then().error()

**Comment by LarssonTech2** [comment]
Hello,

Could you show us an example, we don't understand the above response, we aren't used to promise handling in our Java project. If the promise is properly handling, do you think it will solve our issue https://github.com/voxeet/voxeet-uxkit-android/issues/27#issuecomment-871232731 ?

Greetings.

**Comment by LarssonTech2** [comment]
Hello @codlab, very sorry to ping you, but did you have time to watch at our above question?

Regards.

**Comment by codlab** [comment]
You need to do something like :


```

    private void audioDeviceUpdated(@Nullable List<MediaDevice> mediaDevices) {
        if (null == mediaDevices) return; // need to be checked?

        Promise<Boolean> promise = getConnectIfPossile(mediaDevices, DeviceType.WIRED_HEADSET);

        /* for bluetooth, priority number 2 */
        if (null == promise)
            promise = getConnectIfPossile(mediaDevices, DeviceType.BLUETOOTH);

        /* for External speaker, priority number 3 */
        if (null == promise)
            promise = getConnectIfPossile(mediaDevices, DeviceType.EXTERNAL_SPEAKER);

        if (null != promise) {
            promise.then(aBoolean -> {
                // success
            }).error(error -> {
                // failure
            });
        }
    }

    @Nullable
    private Promise<Boolean> getConnectIfPossile(@NonNull List<MediaDevice> mediaDevices, @NonNull DeviceType deviceType) {
        /* for External speaker, priority number 3 */
        for (MediaDevice mediaDevice : mediaDevices) {
            if (!ConnectionState.CONNECTED.equals(mediaDevice.platformConnectionState())) continue;

            if (deviceType.equals(mediaDevice.deviceType())) { // remove mediaDevice.platformConnectionState() == ConnectionState.CONNECTED as told so.
                if (mediaDevice.connectionState() == ConnectionState.DISCONNECTING || mediaDevice.connectionState() == ConnectionState.DISCONNECTED) {
                    return VoxeetSDK.audio().connect(mediaDevice);  //  maybe promise is useless
                } else if (mediaDevice.connectionState() == ConnectionState.CONNECTING || mediaDevice.connectionState() == ConnectionState.CONNECTED) {
                    return Promise.resolve(true);     //  maybe promise is useless
                }
                return null;
            }
        }
        return null;
    }
```

**Comment by LarssonTech2** [comment]
Thank you Codlab, we are still in test process but it's better working now.
