### ISSUE TITLE
Could not find com.voxeet.sdk:uxkit:3.2.0.

### ISSUE THREAD

**Issue by ShengjieGeng** [voxeet/voxeet-uxkit-android#34]
Sorry to bother you but I really do not know what went wrong when I try to migrate the V2.4.0 to the V3.2.0.
First, I add  `maven { url "https://android-sdk.voxeet.com/release" } ` in build.gradle file at the project layer.
Second, I add the `api ('com.voxeet.sdk:uxkit:3.2.0') { transitive = true }` in build.gradle file at the app layer.
But I run the project when something wrong happened as below:
![image](https://user-images.githubusercontent.com/18364968/139372181-fdcd4f6d-cbcf-428b-a062-c82030db1879.png)

Please do me a favor if you have something to tell me.
Thanks!

**Comment by codlab** [comment]
Inside the logs, you created the conference however you don't try to join it. You either don't use the join method or don't resolve the promise returned by the call

**Comment by ShengjieGeng** [comment]
> Inside the logs, you created the conference however you don't try to join it. You either don't use the join method or don't resolve the promise returned by the call

Yes.
But I tried the code：
`VoxeetSDK.conference().create(getModel().getConference()).then(new JoinPromise()).error(new ConnectFailurePromise());`, which was not receiving anything within the JoinPomise class as below:

```
private class JoinPromise extends DefaultExecPromise<CreateConferenceResult> {

        @Override
        public void onCall(CreateConferenceResult result, Solver<Object> solver) {
            LogUtil.getInstance().w("JoinPromise");
            try {
                if (result != null && result.conferenceId != null) {
                    VoxeetSDK.conference().join(VoxeetSDK.conference().getConference(result.conferenceId)).then(new ConnectPromise()).error(new ConnectFailurePromise());
                } else {
                    onConnectErrorCallback("Invalid Conference.");
                }
            } catch (Exception e) {
                LogUtil.getInstance().w("JoinPromise error: " + e.getMessage());
                onConnectErrorCallback(e);
            }
        }

    }
```

**Comment by codlab** [comment]
The issue here is that you made the class expects a CreateConferenceResult when it's actually a Conference

On a sidenote, you are using a promise which is expecting the resolve its solver, the new version can let you use .then((ThenVoid<ExpectedClass>) object -> { ... });

And when you have intermediates promises you can use the ThenPromise<InputClass, OutputClass>

**Comment by ShengjieGeng** [comment]
> (ThenVoid) object -> { ... }

Thank you very much！
I tried like below：
```
VoxeetSDK.conference().create(getModel().getConference()).then((ThenVoid<Conference>) object -> {
                    try {
                        if (object != null && !TextUtils.isEmpty(object.getId())) {
                            VoxeetSDK.conference().join(VoxeetSDK.conference().getConference(object.getId())).then(new ConnectPromise()).error(new ConnectFailurePromise());
                        } else {
                            onConnectErrorCallback("Invalid Conference.");
                        }
                    } catch (Exception e) {
                        onConnectErrorCallback(e);
                    }
                }).error(new ConnectFailurePromise());
```
then succeed.
